package com.yoyound.sync.stock;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.yoyound.sync.stock.test.*;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void newmapping(ActiveRecordPlugin arp) {
		arp.addMapping("hjmall_attr", "id", Attr.class);
		arp.addMapping("hjmall_attr_group", "id", AttrGroup.class);
		arp.addMapping("hjmall_goods", "id", Goods.class);
		arp.addMapping("hjmall_goods_cat", "id", GoodsCat.class);
		arp.addMapping("hjmall_goods_pic", "id", GoodsPic.class);
	}
	public static void oldmapping(ActiveRecordPlugin arp) {
		arp.addMapping("s_goods_sku", "id", Sku.class);

	}
}

